# 1. Base Image
FROM python:3.11-slim

# 2. Working Directory
WORKDIR /app

# 3. Install App Dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copy Application Source Code
COPY . .

# 5. Expose Network Port
EXPOSE 5000

# 6. Define Runtime Command
CMD ["python", "app.py"]
